### ISSUE TITLE
dse_table_tombstone_scanned_histogram multiplying by 1000

### ISSUE THREAD

**Issue by smlacerda5** [datastax/dse-metric-reporter-dashboards#18]
It's a little misleading that we multiply tombstones by 1000:

`sum(dse_table_tombstone_scanned_histogram{instance=~"$instance", cluster=~"$cluster", dc=~"$dc", rack=~"$rack", keyspace=~"$keyspace", table=~"$table", quantile=~".\\d+"}) by (quantile, instance) * 1000`

Can we remove the multiplication of 1000?

**Comment by tjake** [comment]
Yes! Would you like to make a PR? Otherwise I can do it

**Comment by smlacerda5** [comment]
I don't seem to have access to push any changes, so you're probably better
off doing so.

On Fri, Nov 15, 2019 at 12:48 PM Jake Luciani <notifications@github.com>
wrote:

> Yes! Would you like to make a PR? Otherwise I can do it
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_datastax_dse-2Dmetric-2Dreporter-2Ddashboards_issues_18-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DALEQQWJVUMU6OUFHX5RSDADQT4DI7A5CNFSM4JN73HCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEGVPGQ-23issuecomment-2D554522522&d=DwMCaQ&c=adz96Xi0w1RHqtPMowiL2g&r=R58SsZ6FLB8iCRFGJzNOH0d2HRPVtaWKKj5fzuMiGlo&m=3baFa6TSZfjU46n35YtwfslpyZtdDcSzSPIO8ddRvuw&s=BO8xY8w2rPKvTUF1EVizrbfA9GEF-hFNVfh7lpJnYlg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALEQQWOQT3KCSBXG247GGQ3QT4DI7ANCNFSM4JN73HCA&d=DwMCaQ&c=adz96Xi0w1RHqtPMowiL2g&r=R58SsZ6FLB8iCRFGJzNOH0d2HRPVtaWKKj5fzuMiGlo&m=3baFa6TSZfjU46n35YtwfslpyZtdDcSzSPIO8ddRvuw&s=_B9Un1WsvC9GB-Yt3T34FHhYR2Mi3nzIrhCF26MrxW4&e=>
> .
>


-- 
Steve Lacerda | Technical Support Engineer
office +1.408.933.3102 | mobile +1. 669.377.9742
steve.lacerda@datastax.com | datastax.com

<https://twitter.com/datastax> <https://www.linkedin.com/company/datastax/>
<https://www.facebook.com/datastax> <http://feeds.feedburner.com/datastax>
<https://github.com/datastax/>

<http://goog_1784100713>
<http://datastax.com>

**Comment by tjake** [comment]
Done in 5187d7720c0f82c753cb6234eff8656914070d30 Thanks
